// Brand theme for the flag-gated landlord redesign (§2/§3.1 of
// docs/product/LANDLORD_REDESIGN_SPEC.md).
//
// Fluent UI v9's `createLightTheme(BrandVariants)` API expects a 16-step
// color ramp (steps 10..160), while `packages/brand` defines only a single
// flat hex per brand color. This module generates that ramp from the four
// approved brand hexes, anchored so that a *named, documented* step
// reproduces the exact approved hex (per the spec's binding instruction),
// rather than leaving ramp generation to an unreviewed interpolation.
//
// Anchor choice: Fluent's own `createLightTheme` implementation
// (@fluentui/tokens `alias/lightColor.js`) maps `colorBrandBackground`,
// `colorBrandForeground1`, and `colorBrandStroke1` to `brand[80]` — the
// step actually used for primary buttons/active states. Step 80 is
// therefore pinned to the exact `mineralTeal` hex (#267C78), matching the
// spec's suggestion in §2. All other steps are generated by mixing the
// anchor color with white (lighter steps, 10-70) or black (darker steps,
// 90-160) at the documented percentages below — a deterministic,
// traceable-to-source transform, not a black-box generator. This ramp
// still requires the human visual review called for in §2/§8d before any
// production rollout; it is reviewable directly from the mix table here.
import { createLightTheme } from '@fluentui/react-components';
import { keyfortaBrand } from '@keyforta/brand';

function hexToRgb(hex) {
  const normalized = hex.replace('#', '');
  return {
    r: parseInt(normalized.slice(0, 2), 16),
    g: parseInt(normalized.slice(2, 4), 16),
    b: parseInt(normalized.slice(4, 6), 16),
  };
}

function rgbToHex({ r, g, b }) {
  const toHex = (value) => Math.round(Math.min(255, Math.max(0, value))).toString(16).padStart(2, '0');
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`.toUpperCase();
}

function mix(hex, targetHex, weight) {
  const from = hexToRgb(hex);
  const to = hexToRgb(targetHex);
  return rgbToHex({
    r: from.r + (to.r - from.r) * weight,
    g: from.g + (to.g - from.g) * weight,
    b: from.b + (to.b - from.b) * weight,
  });
}

// Documented white/black mix weight per ramp step. Step 80 (weight 0) is
// the exact approved brand hex; every other step is a deterministic mix
// toward white (lighter, steps 10-70) or black (darker, steps 90-160).
const RAMP_MIX = {
  10: { toward: '#FFFFFF', weight: 0.92 },
  20: { toward: '#FFFFFF', weight: 0.82 },
  30: { toward: '#FFFFFF', weight: 0.7 },
  40: { toward: '#FFFFFF', weight: 0.56 },
  50: { toward: '#FFFFFF', weight: 0.42 },
  60: { toward: '#FFFFFF', weight: 0.28 },
  70: { toward: '#FFFFFF', weight: 0.14 },
  80: { toward: '#FFFFFF', weight: 0 },
  90: { toward: '#000000', weight: 0.1 },
  100: { toward: '#000000', weight: 0.2 },
  110: { toward: '#000000', weight: 0.3 },
  120: { toward: '#000000', weight: 0.4 },
  130: { toward: '#000000', weight: 0.5 },
  140: { toward: '#000000', weight: 0.6 },
  150: { toward: '#000000', weight: 0.7 },
  160: { toward: '#000000', weight: 0.8 },
};

export function generateBrandRamp(anchorHex) {
  const ramp = {};
  for (const [step, { toward, weight }] of Object.entries(RAMP_MIX)) {
    ramp[Number(step)] = weight === 0 ? anchorHex.toUpperCase() : mix(anchorHex, toward, weight);
  }
  return ramp;
}

// Named, reviewable brand ramp (§2). `mineralTealRamp[80]` is asserted (in
// this file's paired unit test) to equal the exact approved hex.
export const mineralTealRamp = generateBrandRamp(keyfortaBrand.colors.mineralTeal);

export const landlordRedesignTheme = {
  ...createLightTheme(mineralTealRamp),
  // Brand surfaces per §3.1/§3.4 — not part of Fluent's brand ramp (those
  // only cover the single interactive accent color), applied as CSS custom
  // properties consumed by redesign.css.
  colorPortalAubergine: keyfortaBrand.colors.aubergine,
  colorPortalMineralTeal: keyfortaBrand.colors.mineralTeal,
  colorPortalBurnishedCopper: keyfortaBrand.colors.burnishedCopper,
  colorPortalSoftBone: keyfortaBrand.colors.softBone,
  fontFamilyPortalDisplay: `'${keyfortaBrand.fonts.display}', 'Segoe UI', sans-serif`,
  fontFamilyPortalBody: `'${keyfortaBrand.fonts.body}', 'Segoe UI', sans-serif`,

  // §11.4 — explicit override of Fluent's default neutral-gray *resting*
  // border tokens for Input/Select/Textarea (confirmed against
  // @fluentui/react-input's compiled styles: the root slot's `border`
  // shorthand reads `colorNeutralStroke1`, and its `border-bottom-color`
  // reads `colorNeutralStrokeAccessible` — both are overridden here, not
  // only the hover/focus tokens, which is the "common integration
  // mistake" §11.4 explicitly calls out to avoid). Values are an
  // aubergine tint (no new hue), verified in-browser via the Playwright
  // screenshot evidence, not assumed from the token names alone.
  colorNeutralStroke1: 'rgba(36, 22, 46, 0.32)',
  colorNeutralStroke1Hover: 'rgba(36, 22, 46, 0.48)',
  colorNeutralStroke1Pressed: 'rgba(36, 22, 46, 0.56)',
  colorNeutralStrokeAccessible: 'rgba(36, 22, 46, 0.45)',
  colorNeutralStrokeAccessibleHover: 'rgba(36, 22, 46, 0.6)',
  colorNeutralStrokeAccessiblePressed: 'rgba(36, 22, 46, 0.68)',
};
