const SESSION_KEY = 'keyforta.portal.session';
const roles = {
  tenant: { label: 'Tenant', eyebrow: 'My rental', title: 'Everything about your home, in one place.', summary: 'Track your application, lease, payments, maintenance, documents, and messages.', nav: ['Overview', 'My lease', 'Payments', 'Maintenance', 'Documents', 'Messages'], stats: [['Next rent', '$400', 'Due in 8 days'], ['Lease', 'Active', 'Riverside apartment'], ['Open request', '1', 'Water pump inspection']], rows: [['Maintenance request', 'Water pump inspection', 'In progress', 'Maintenance'], ['Payment', 'May rent · receipt #KF-1042', 'Recorded', 'Payments'], ['Message', 'Manager replied about your viewing', 'New', 'Messages']] },
  landlord: { label: 'Landlord', eyebrow: 'Owner workspace', title: 'A clear view of your property portfolio.', summary: 'Manage properties, units, applications, leases, rent, maintenance, documents, and your manager relationships.', nav: ['Overview', 'Properties', 'Applications', 'Leases', 'Payments', 'Maintenance', 'Documents', 'Messages'], stats: [['Properties', '3', 'Kinshasa portfolio'], ['Occupancy', '83%', '5 of 6 units'], ['Collected', '$1,850', 'This month'], ['Open maintenance', '2', 'Needs attention']], rows: [['Rental application', 'Riverside apartment · Amina K.', 'Awaiting review', 'Applications'], ['Payment', 'May rent · 5 occupied units', 'Reconciled', 'Payments'], ['Manager invitation', 'Patrick M. · Property manager', 'Pending acceptance', 'Messages']] },
  manager: { label: 'Property manager', eyebrow: 'Operations workspace', title: 'Coordinate the work behind every home.', summary: 'Operate the assigned portfolio while keeping applications, occupants, payments, maintenance, documents, and communication connected.', nav: ['Overview', 'Portfolio', 'Applications', 'Occupancy', 'Payments', 'Work orders', 'Documents', 'Messages'], stats: [['Assigned units', '14', 'Across 4 properties'], ['Applications', '3', 'Waiting for review'], ['Open work orders', '4', 'Across 3 properties'], ['Payments', '5', 'To reconcile']], rows: [['Application', 'Amina K. · Riverside apartment', 'Review required', 'Applications'], ['Work order', 'Generator maintenance · Gombe', 'Assigned', 'Work orders'], ['Document', 'Ownership evidence · Limete', 'Needs review', 'Documents']] },
  technician: { label: 'Independent maintenance operator', eyebrow: 'Field workspace', title: 'Move every assigned job forward.', summary: 'Offer your services across properties, then manage only the jobs, access windows, quotes, reports, and evidence assigned to you.', nav: ['Overview', 'Service offers', 'Work orders', 'Schedule', 'Quotes', 'Reports', 'Earnings', 'Profile'], stats: [['Assigned jobs', '3', 'Across 2 properties'], ['Today', '2 visits', 'One confirmed'], ['Quotes', '1', 'Due before 17:00'], ['Earnings', '$1,240', 'This month']], rows: [['Work order', 'Water pump inspection · Ngaliema', 'Assigned', 'Work orders'], ['Visit', 'Generator maintenance · Gombe', 'Today, 14:00–15:00', 'Schedule'], ['Quote', 'Pump materials and labor', 'Draft', 'Quotes']] }
};
const app = document.querySelector('#app');
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const readSession = () => { try { return JSON.parse(localStorage.getItem(SESSION_KEY) || 'null'); } catch { return null; } };
const saveSession = (session) => localStorage.setItem(SESSION_KEY, JSON.stringify(session));
const loginView = () => `<div class="auth-layout"><section class="auth-card"><div class="brand">KEYFORTA <span>/ PORTAL</span></div><p class="kicker">Protected workspace</p><h1>Sign in to continue.</h1><p class="muted">Choose a demo role to explore the frontend that will connect to the Keyforta API.</p><div class="demo-grid">${Object.entries(roles).map(([value, role]) => `<button class="demo-choice" data-demo-role="${value}"><span>${role.label}</span><small>${role.summary}</small></button>`).join('')}</div><p class="notice"><strong>Demo mode.</strong> No password or real account is used here. Production authentication and authorization will be enforced by the backend.</p></section></div>`;
const sidebar = (role, active) => `<aside class="sidebar"><div class="brand">KEYFORTA <span>/ PORTAL</span></div><div class="workspace-label">${role.eyebrow}</div><nav aria-label="Workspace navigation">${role.nav.map((item, index) => `<button class="nav-item ${index === 0 || item === active ? 'active' : ''}" data-section="${item}"><span class="nav-icon">${['⌂', '▦', '✓', '◷', '$', '⚒', '▤', '✉'][index % 8]}</span>${item}</button>`).join('')}</nav><button class="signout" id="logout">Sign out</button></aside>`;
const quickActions = (role) => ({ tenant: [['Report a maintenance issue', 'maintenance'], ['Upload a document', 'document'], ['Message manager', 'message']], landlord: [['Add a property', 'property'], ['Invite a manager', 'invite'], ['Review applications', 'applications']], manager: [['Review an application', 'applications'], ['Create work order', 'maintenance'], ['Record a payment', 'payment']], technician: [['Publish a service offer', 'offer'], ['Accept a work order', 'accept'], ['Submit a quote', 'quote']] }[role] || []);
const workspaceView = (session, active = 'Overview') => { const role = roles[session.role] || roles.tenant; return `<div class="app-shell">${sidebar(role, active)}<main class="main"><header class="topbar"><div><p class="kicker">${role.eyebrow}</p><h1>${active === 'Overview' ? role.title : active}</h1><p class="muted">${active === 'Overview' ? role.summary : `Your ${active.toLowerCase()} records and actions.`}</p></div><div class="user-chip"><span class="avatar">${escapeHtml(session.email.slice(0, 1).toUpperCase())}</span><span>${escapeHtml(session.email)}</span></div></header><div class="demo-strip"><span class="dot"></span><strong>Demo data</strong><span>Actions are local previews until the API is connected.</span></div><section class="stats">${role.stats.map(([label, value, note]) => `<article class="stat"><span>${label}</span><strong>${value}</strong><small>${note}</small></article>`).join('')}</section><section class="content-grid"><article class="panel table-panel"><div class="panel-head"><div><p class="kicker">Activity</p><h2>Needs your attention</h2></div><button class="quiet" data-action="new">New action</button></div><div class="rows">${role.rows.map(([type, title, status, destination]) => `<button class="record-row" data-section="${destination}"><span class="record-type">${type}</span><span class="record-copy"><strong>${title}</strong><small>${destination}</small></span><span class="status">${status}</span><span class="chevron">›</span></button>`).join('')}</div></article><aside class="panel quick-panel"><p class="kicker">Quick actions</p><h2>Keep things moving.</h2><div class="quick-actions">${quickActions(session.role).map(([label, action]) => `<button data-action="${action}"><span>${label[0]}</span>${label}</button>`).join('')}</div><div class="api-note"><strong>API boundary</strong><p>Every action maps to a command or resource in the shared contract. The server remains authoritative.</p></div></aside></section></main></div>`; };
function render(active) { const session = readSession(); app.innerHTML = session ? workspaceView(session, active) : loginView(); if (!session) document.querySelectorAll('[data-demo-role]').forEach((button) => button.addEventListener('click', () => { saveSession({ email: `demo.${button.dataset.demoRole}@test.keyforta.com`, role: button.dataset.demoRole, issuedAt: new Date().toISOString() }); render(); })); else { document.querySelectorAll('[data-section]').forEach((button) => button.addEventListener('click', () => render(button.dataset.section))); document.querySelector('#logout').addEventListener('click', () => { localStorage.removeItem(SESSION_KEY); render(); }); document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => { button.textContent = 'Saved in demo'; setTimeout(() => { button.textContent = button.dataset.action === 'new' ? 'New action' : 'Done'; }, 900); })); } }
render();
