// Brand theme for the flag-gated Admin redesign
// (docs/product/ADMIN_REDESIGN_SPEC.md §2/§3.1/§8a).
//
// ---------------------------------------------------------------------
// Labeled, reversible engineering default (spec §8a; mirrors the
// softened, non-authoritative language pattern already used by
// `docs/product/MANAGER_REDESIGN_SPEC.md` §8.1, not a silent resolution
// of §8a's still-open shared-component-location question):
//
// `apps/admin-web` is a separate Vite app/workspace package
// (`@keyforta/admin-web`) from the sibling Portal front-end application
// (the sibling application's own workspace package) with a separate build root, so there is no
// relative-import path from this file's location to that application's
// own Landlord-phase theme module at all (see spec §1 for its exact
// path — unlike Manager and Tenant, which import that file directly
// since they live inside the same app). The spec's §8a names exactly two
// real options for this phase: (i) extract the ramp/theme into a proper
// shared workspace package (most plausibly `packages/ui`), or (ii)
// duplicate the small, deterministic values into a new, Admin-local file.
//
// This implementation takes option (ii) — duplicating this file's ~40
// lines of deterministic, reviewable ramp-generation logic and the same
// anchor-hex documentation below, unmodified in substance — as the
// narrower, more reversible engineering default for this phase, not as a
// resolution of §8a. §8a is intentionally left open for the Solution
// Architect/Product Owner, exactly as the spec requires; if a shared
// package is extracted later, this file is deleted and replaced with an
// import from that package, and (per the spec's closing §8a note) that
// migration should apply to Manager's and Tenant's own still-open
// `../landlord/theme.js` imports as well, not just this file.
// ---------------------------------------------------------------------
//
// Fluent UI v9's `createLightTheme(BrandVariants)` API expects a 16-step
// color ramp (steps 10..160), while `packages/brand` defines only a single
// flat hex per brand color. This module generates that ramp from the four
// approved brand hexes, anchored so that a *named, documented* step
// reproduces the exact approved hex, rather than leaving ramp generation
// to an unreviewed interpolation.
//
// Anchor choice: Fluent's own `createLightTheme` implementation
// (@fluentui/tokens `alias/lightColor.js`) maps `colorBrandBackground`,
// `colorBrandForeground1`, and `colorBrandStroke1` to `brand[80]` — the
// step actually used for primary buttons/active states. Step 80 is
// therefore pinned to the exact `mineralTeal` hex (#267C78), matching
// `LANDLORD_REDESIGN_SPEC.md` §2. All other steps are generated by mixing
// the anchor color with white (lighter steps, 10-70) or black (darker
// steps, 90-160) at the documented percentages below — a deterministic,
// traceable-to-source transform, not a black-box generator. This ramp
// still requires the same human visual review called for by the Landlord
// spec §2/§8d before any production rollout; it is reviewable directly
// from the mix table here.
import { createLightTheme } from '@fluentui/react-components';
import { keyfortaBrand } from '@keyforta/brand';

function hexToRgb(hex) {
  const normalized = hex.replace('#', '');
  return {
    r: parseInt(normalized.slice(0, 2), 16),
    g: parseInt(normalized.slice(2, 4), 16),
    b: parseInt(normalized.slice(4, 6), 16),
  };
}

function rgbToHex({ r, g, b }) {
  const toHex = (value) => Math.round(Math.min(255, Math.max(0, value))).toString(16).padStart(2, '0');
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`.toUpperCase();
}

function mix(hex, targetHex, weight) {
  const from = hexToRgb(hex);
  const to = hexToRgb(targetHex);
  return rgbToHex({
    r: from.r + (to.r - from.r) * weight,
    g: from.g + (to.g - from.g) * weight,
    b: from.b + (to.b - from.b) * weight,
  });
}

// Documented white/black mix weight per ramp step. Step 80 (weight 0) is
// the exact approved brand hex; every other step is a deterministic mix
// toward white (lighter, steps 10-70) or black (darker, steps 90-160).
const RAMP_MIX = {
  10: { toward: '#FFFFFF', weight: 0.92 },
  20: { toward: '#FFFFFF', weight: 0.82 },
  30: { toward: '#FFFFFF', weight: 0.7 },
  40: { toward: '#FFFFFF', weight: 0.56 },
  50: { toward: '#FFFFFF', weight: 0.42 },
  60: { toward: '#FFFFFF', weight: 0.28 },
  70: { toward: '#FFFFFF', weight: 0.14 },
  80: { toward: '#FFFFFF', weight: 0 },
  90: { toward: '#000000', weight: 0.1 },
  100: { toward: '#000000', weight: 0.2 },
  110: { toward: '#000000', weight: 0.3 },
  120: { toward: '#000000', weight: 0.4 },
  130: { toward: '#000000', weight: 0.5 },
  140: { toward: '#000000', weight: 0.6 },
  150: { toward: '#000000', weight: 0.7 },
  160: { toward: '#000000', weight: 0.8 },
};

export function generateBrandRamp(anchorHex) {
  const ramp = {};
  for (const [step, { toward, weight }] of Object.entries(RAMP_MIX)) {
    ramp[Number(step)] = weight === 0 ? anchorHex.toUpperCase() : mix(anchorHex, toward, weight);
  }
  return ramp;
}

// Named, reviewable brand ramp. `mineralTealRamp[80]` is asserted (in this
// file's paired unit test) to equal the exact approved hex.
export const mineralTealRamp = generateBrandRamp(keyfortaBrand.colors.mineralTeal);

export const adminRedesignTheme = {
  ...createLightTheme(mineralTealRamp),
  // Brand surfaces per Landlord §3.1/§3.4 — not part of Fluent's brand
  // ramp (those only cover the single interactive accent color), applied
  // as CSS custom properties consumed by redesign.css.
  colorPortalAubergine: keyfortaBrand.colors.aubergine,
  colorPortalMineralTeal: keyfortaBrand.colors.mineralTeal,
  colorPortalBurnishedCopper: keyfortaBrand.colors.burnishedCopper,
  colorPortalSoftBone: keyfortaBrand.colors.softBone,
  fontFamilyPortalDisplay: `'${keyfortaBrand.fonts.display}', 'Segoe UI', sans-serif`,
  fontFamilyPortalBody: `'${keyfortaBrand.fonts.body}', 'Segoe UI', sans-serif`,

  // Landlord §11.4 — explicit override of Fluent's default neutral-gray
  // *resting* border tokens for Input/Select/Textarea, applied here so
  // Admin's decision-reason/reviewer-notes `Textarea`s match the same
  // aubergine-tint border treatment already shipped for Landlord/Manager/
  // Tenant.
  colorNeutralStroke1: 'rgba(36, 22, 46, 0.32)',
  colorNeutralStroke1Hover: 'rgba(36, 22, 46, 0.48)',
  colorNeutralStroke1Pressed: 'rgba(36, 22, 46, 0.56)',
  colorNeutralStrokeAccessible: 'rgba(36, 22, 46, 0.45)',
  colorNeutralStrokeAccessibleHover: 'rgba(36, 22, 46, 0.6)',
  colorNeutralStrokeAccessiblePressed: 'rgba(36, 22, 46, 0.68)',
};
